version: "3.4"

services:
  db:
    image: gvenzl/oracle-free:latest
    environment:
      - ORACLE_PASSWORD=pass
      - APP_USER=maria
      - APP_USER_PASSWORD=pass
    ports:
      - 1521

  py-srv:
    build: py-srv
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python app.py"
    environment:
      - NEO4J_AUTH=neo4j/secret
      - WAIT_HOSTS=db:1521
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "80:5000"
      
  py-test-srv:
    build:
      context: py-test-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:1521,py-srv:5000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - py-srv
    links:
      - "py-srv:py-srv"
